<?php

/**
 * @file
 * Primary module hooks for WaterAid Content module.
 */

use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\Core\Form\FormStateInterface;
use Drupal\datetime\Plugin\Field\FieldType\DateTimeItemInterface;
use Drupal\paragraphs\ParagraphInterface;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;
use Drupal\views\Views;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function wateraid_content_form_node_form_alter(&$form, FormStateInterface $form_state): void {
  if (isset($form['field_review_date'])) {
    if (wateraid_content_review_date_form_access($form, $form_state)) {
      if ($form['field_review_date']['widget'][0]['value']) {
        // Set a date range that can be no more than +2 years.
        $date = new DrupalDateTime();

        $form['field_review_date']['widget'][0]['value']['#date_year_range'] = $date->format('Y') . ':';

        $interval = DateInterval::createFromDateString('+2 years');
        $date->add($interval);

        $form['field_review_date']['widget'][0]['value']['#date_year_range'] .= $date->format('Y');
        $form['field_review_date']['#element_validate'][] = 'wateraid_content_review_date_validate';
      }
    }
    else {
      $form['field_review_date']['#access'] = FALSE;
      $form['field_review_date']['widget']['#required'] = FALSE;
      $form['field_review_date']['widget'][0]['#required'] = FALSE;
      $form['field_review_date']['widget'][0]['value']['#required'] = FALSE;
    }
  }

  if (isset($form['field_metatags']['widget'][0]['basic']['description']['#description'])) {
    $form['field_metatags']['widget'][0]['basic']['description']['#description'] = t("A brief and concise summary of the page's content that is a maximum of 160 characters in length. The description meta tag may be used by search engines to display a snippet about the page in search results. Set to %none to disable inheritance of the parent value and prevent the output of this metatag entirely. Unless edited, this will automatically populate from the Teaser text field.", [
      '%none' => '<none>',
    ]);
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function wateraid_content_paragraph_presave(ParagraphInterface $paragraph): void {
  if ($paragraph->hasField('field_image')) {
    if ($medias = $paragraph->get('field_image')->referencedEntities()) {

      /** @var \Drupal\media\MediaInterface $media */
      if ($media = reset($medias)) {
        foreach (['field_caption', 'field_credit'] as $field) {
          if ($media->hasField($field) && $paragraph->hasField($field) && $paragraph->get($field)->isEmpty()) {
            $paragraph->set($field, $media->get($field)->getValue());
          }
        }
      }
    }
  }
}

/**
 * Helper to calculate if the user has access to see the review date field.
 *
 * @param array $form
 *   The node edit form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 *
 * @return bool
 *   TRUE if they have access, FALSE (default) if not.
 */
function wateraid_content_review_date_form_access(array $form, FormStateInterface $form_state): bool {
  $current_user = \Drupal::currentUser();

  // Root user can always override.
  if ($current_user->id() == 1) {
    return TRUE;
  }

  $roles = $current_user->getRoles(TRUE);

  // Administrators or WaterAid Super Admins can view all expiry dates.
  if (in_array('administrator', $roles) || in_array('wateraid_super_admin', $roles)) {
    return TRUE;
  }

  /** @var \Drupal\node\NodeInterface $node */
  $node = $form_state->getFormObject()->getEntity();

  // If the node is being created, the user will be the owner and so will have
  // access to the field.
  if ($node->isNew()) {
    return TRUE;
  }

  if (in_array('content_editor', $roles)) {

    // WaterAid Administrators can see their own nodes.
    if ($node->getOwnerId() == $current_user->id()) {
      return TRUE;
    }

    // Co-authors can view the review date.
    if ($co_authors = $node->get('co_authors')->getValue()) {
      if (isset($co_authors['0']) && in_array($current_user->id(), $co_authors[0])) {
        return TRUE;
      }
    }
  }

  return FALSE;
}

/**
 * Validates the Review Date.
 *
 * @param array $element
 *   The review date field form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The node form form state.
 */
function wateraid_content_review_date_validate(array &$element, FormStateInterface $form_state): void {
  if ($date = $form_state->getValue('field_review_date')) {
    if (isset($date[0]['value'])) {

      /** @var \Drupal\Core\Datetime\DrupalDateTime $date */
      $date = $date[0]['value'];

      // Normalise the dates to the same timezone and hours as it's only the
      // dates we're interested in.
      $date->setTime(0, 0, 1);
      $now = new DrupalDateTime('now', 'UTC');
      $now->setTime(0, 0, 1);

      if ($date < $now) {
        $form_state->setError($element, t('Review Date cannot be before today.'));
      }

      $interval = DateInterval::createFromDateString('+2 years');
      $now->add($interval);

      if ($date > $now) {
        $form_state->setError($element, t('Review Date must be less than 2 years in the future.'));
      }
    }
  }
}

/**
 * Implements hook_views_query_alter().
 */
function wateraid_content_views_query_alter(ViewExecutable $view, QueryPluginBase $query): void {
  if ($view->id() == 'content_review_dashboard') {
    $current_user = \Drupal::currentUser();

    // If the user is a WaterAid Administrator, they can only see the content
    // they own.
    if (in_array('content_editor', $current_user->getRoles(TRUE))) {
      $configuration = [
        'type'       => 'LEFT',
        'table'      => 'node__co_authors',
        'field'      => 'entity_id',
        'left_table' => 'node_field_data',
        'left_field' => 'nid',
        'operator'   => '=',
      ];

      /** @var \Drupal\views\Plugin\views\join\JoinPluginBase $join */
      $join = Views::pluginManager('join')->createInstance('standard', $configuration);
      $query->addTable('node__co_authors', NULL, $join, 'node__co_authors');

      // The count of the current where conditions plus one will give us the
      // next available group number.
      $group = count($query->where) + 1;

      // We'll add where conditions for the co-authors and node owner fields.
      foreach (['node__co_authors.co_authors_target_id', 'node_field_data.uid'] as $field) {
        $query->addWhere($group, $field, $current_user->id());
      }

      // Set the group to be an OR group.
      $query->setWhereGroup('OR', $group);
    }
  }
}

/**
 * Implements hook_form_layout_paragraphs_component_form_alter().
 */
function wateraid_content_form_layout_paragraphs_component_form_alter(array &$form, FormStateInterface &$form_state): void {
  if (isset($form['field_quote_type'])) {
    wateraid_content_update_field_widget($form, ['field_image', 'field_caption', 'field_credit'], 'field_quote_type', 'text_only', 'invisible');
  }
  if (isset($form['field_variant'])) {
    wateraid_content_update_field_widget($form, ['field_video'], 'field_variant', 'video', 'visible');
    wateraid_content_update_field_widget($form, ['field_image', 'field_caption', 'field_credit'], 'field_variant', 'image', 'visible');
  }
  if (isset($form['field_media_type'])) {
    wateraid_content_update_field_widget($form, ['field_video'], 'field_media_type', 'video', 'visible');
    wateraid_content_update_field_widget($form, ['field_image', 'field_caption', 'field_credit'], 'field_media_type', 'image', 'visible');
  }
  if (isset($form['field_hero_variant'])) {
    wateraid_content_update_field_widget($form, ['field_video'], 'field_hero_variant', 'hero_with_video', 'visible');
    wateraid_content_update_field_widget($form, ['field_image', 'field_caption', 'field_credit'], 'field_hero_variant', 'hero_with_image', 'visible');
  }

  if (isset($form['field_image_crop'])) {
    $form['field_image_crop']['#attributes'] = ['hidden'=> 'true'];
  }

  // Attach image cropper library to hero_image paragraphs.
  /** @var \Drupal\paragraphs\ParagraphInterface $paragraph */
  $paragraph = $form_state->getFormObject()->getParagraph();
  if ($paragraph->bundle() === 'hero_image' && isset($form['field_image'])) {
    $form['#attached']['library'][] = 'wateraid_content/image_cropper';
  }

  if (isset($form['field_image_crop'])) {
    $form['#attached']['library'][] = 'wateraid_content/image_cropper';
  }
  // echo '<pre>';
  // die(var_dump(
  //   array_keys($form),
  //   $form['#form_id'],
  //   $form['form_id'],
  // ));
}

/**
 * Helper to set the states api implementation for a widget form.
 *
 * @param array $element
 *   The Paragraph form.
 * @param array $fields
 *   An array of fields to add states to.
 * @param string $target_field
 *   The Target field's machine name.
 * @param string $value
 *   The value to use
 * @param string $state
 *   The state to use: visible, invisible, etc.
 */
function wateraid_content_update_field_widget(array &$element, array $fields, string $target_field, string $value, string $state): void {
  foreach ($fields as $field) {
    if (isset($element[$field])) {
      $element[$field]['#states'] = [
        $state => [
          ':input[name="' . $target_field . '"]' => ['value' => $value],
        ],
      ];
    }
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function wateraid_content_theme_suggestions_paragraph_alter(array &$suggestions, array &$variables): void {
  if ($variables['elements']['#paragraph']->hasField('field_quote_type')) {
    $suggestions[] = 'paragraph__' . $variables['elements']['#paragraph']->bundle() . '__' . $variables['elements']['#paragraph']->get('field_quote_type')->getString();
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function wateraid_content_preprocess_paragraph__related_content(&$variables): void {

  /** @var \Drupal\paragraphs\ParagraphInterface $paragraph */
  $paragraph = $variables['paragraph'];

  // Only get published nodes.
  $query = \Drupal::database()->select('node_field_data', 'n')
    ->fields('n', ['nid', 'created']);
  $query->condition('n.status', 1);
  $query->groupBy('n.nid');
  $query->groupBy('n.created');

  if ($group = \Drupal::routeMatch()->getParameter('group')) {
    $query->leftJoin('group_relationship_field_data', 'g', 'n.nid = entity_id AND g.gid = ' . $group->id());
    $query->isNotNull('g.gid');
    $query->condition('g.plugin_id', 'group_node%', 'LIKE');
  }

  // Calculate the total results we'll need.
  $rows = (int) $paragraph->get('field_rows')->getString();
  $columns = (int) $paragraph->get('field_card_columns')->getString();
  $query->range(0, $rows * $columns);

  $event_sort = TRUE;

  // Filter by content type if we need to.
  if (!$paragraph->get('field_content_types')->isEmpty()) {
    $types = explode(', ', $paragraph->get('field_content_types')->getString());
    $query->condition('n.type', $types, 'IN');

    if (!in_array('event', $types)) {
      $event_sort = FALSE;
    }
  }

  if ($event_sort) {
    $query->leftJoin('node__field_event_start_date', 'es', 'n.nid = es.entity_id');
    $query->addField('es', 'field_event_start_date_value');
    $query->orderBy('es.field_event_start_date_value');
    $query->groupBy('es.field_event_start_date_value');

    $or = $query->orConditionGroup();
    $or->isNull('es.field_event_start_date_value');

    $now = new DrupalDateTime();
    $or->condition('es.field_event_start_date_value', $now->format(DateTimeItemInterface::DATETIME_STORAGE_FORMAT), '>=');
    $query->condition($or);
  }

  $query->orderBy('n.created', 'DESC');

  // Set up any taxonomy term filters.
  $filtered = FALSE;
  $conditions = ($paragraph->get('field_match_all_terms')->getString() == 'and') ? $query->andConditionGroup() : $query->orConditionGroup();

  foreach ([
    'field_audience',
    'field_get_involved',
    'field_country',
    'field_event_type',
    'field_subject_area',
    'field_themes',
    'field_topic',
  ] as $field) {
    if (!$paragraph->get($field)->isEmpty()) {
      $filtered = TRUE;
      $values = explode(', ', $paragraph->get($field)->getString());
      $node_field = ($field == 'field_themes') ? 'field_theme' : $field;

      foreach ($values as $key => $value) {
        $alias = $field . $key;
        $query->leftJoin('node__' . $node_field, $alias, $alias . '.entity_id = n.nid');
        $conditions->condition($alias . '.' . $node_field . '_target_id', $value);
      }
    }
  }

  // If any taxonomy filters have been set, add them to the query.
  if ($filtered) {
    $query->condition($conditions);
  }

  if ($nids = $query->execute()->fetchAllKeyed(0, 0)) {
    $nodes = \Drupal::entityTypeManager()->getStorage('node')->loadMultiple($nids);

    /** @var \Drupal\node\NodeViewBuilder $node_view_builder */
    $node_view_builder = \Drupal::entityTypeManager()->getViewBuilder('node');

    // viewMultiple() exists as a method, but using it breaks the theming
    // somehow, so we'll do this individually.
    foreach ($nodes as $node) {
      $variables['content']['field_cards'][] = $node_view_builder->view($node, 'signposting', \Drupal::languageManager()->getCurrentLanguage()->getId());
    }
  }
  else {
    $variables['content']['field_cards'] = [];
  }

  // Any node being edited could make it valid to appear in the listing, so
  // we'll use a very loose cache tag.
  $variables['content']['#cache']['tags'][] = 'node_list';
}

/**
 * Implements hook_field_widget_complete_WIDGET_TYPE_form_alter().
 */
function wateraid_content_field_widget_complete_boolean_checkbox_form_alter(&$field_widget_complete_form, FormStateInterface $form_state, $context): void {
  if (isset($field_widget_complete_form['widget']['#field_name']) && $field_widget_complete_form['widget']['#field_name'] == 'field_show_read_time') {
    $field_widget_complete_form['#attached']['library'][] = 'wateraid_content/hero';
  }
}
