<?php

/**
 * @file
 * Hooks for wateraid_core module.
 */

use Drupal\Core\Render\BubbleableMetadata;
use Drupal\pathauto\Entity\PathautoPattern;
use Drupal\pathauto\PathautoPatternInterface;

/**
 * Implements hook_pathauto_pattern_alter().
 */
function wateraid_core_pathauto_pattern_alter(PathautoPatternInterface $pattern, array $context): void {
  // Only alter for node patterns.
  if ($context['module'] !== 'node' || empty($context['data']['node'])) {
    return;
  }

  /** @var \Drupal\node\NodeInterface $node */
  $node = $context['data']['node'];
  if ($node->bundle() === 'webform') {
    $has_donate_webform = FALSE;
    /** @var \Drupal\webform\WebformInterface|false $webform */
    $webform = !$node->get('webform')->isEmpty() ? $node->get('webform')->first()->entity : FALSE;
    if ($webform && in_array('Donation', $webform->get('categories'))) {
      $has_donate_webform = TRUE;
    }
    // If the webform node type references a donate webform, we change the
    // pathauto path.
    if ($has_donate_webform) {
      $pattern->setPattern(PathautoPattern::load('webform_with_donate_form')->getPattern());
    }
    else {
      $pattern->setPattern(PathautoPattern::load('webform')->getPattern());
    }
  }
}

/**
 * Implements hook_token_info_alter().
 */
function wateraid_core_token_info_alter(&$data): void {
  $data['tokens']['group_relationship']['node'] = [
    'name' => t('Relationship Content'),
    'description' => t('The content linked to the group.'),
    'module' => 'wateraid_core',
    'type' => 'node',
  ];
}

/**
 * Implements hook_tokens().
 */
function wateraid_core_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata): array {
  $replacements = [];

  if (isset($data['entity_type']) && $data['entity_type'] == 'group_relationship') {
    $token_service = \Drupal::token();

    /** @var \Drupal\group\Entity\GroupRelationshipInterface $relationship */
    $relationship = $data['entity'];

    if ($node_tokens = $token_service->findWithPrefix($tokens, 'node')) {
      $replacements += $token_service->generate('node', $node_tokens, ['node' => $relationship->getEntity()], $options, $bubbleable_metadata);
    }
  }

  return $replacements;
}
