field.widget.settings.group_webform_entity_reference_select:
  type: mapping
  label: 'Webform select display format settings'
  mapping:
    default_data:
      type: boolean
      label: 'Default submission data'
    webforms:
      type: sequence
      label: 'Webforms'
      sequence:
        type: string
        label: 'Webform'
