<?php

/**
 * @file
 * Module file for WaterAid TMGMT.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_entity_base_field_info().
 */
function wateraid_tmgmt_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'tmgmt_message') {
    $fields['email_notification_timestamp'] = BaseFieldDefinition::create('timestamp')
      ->setLabel(t('Email notification timestamp'));

    return $fields;
  }
}

/**
 * Implements hook_cron().
 */
function wateraid_tmgmt_cron(): void {
  /** @var \Drupal\wateraid_tmgmt\EmailNotificationManager $email_notification_manager */
  $email_notification_manager = Drupal::service('wateraid_tmgmt.email_notification_manager');
  $email_notification_manager->generateNotificationEmails();
}

/**
 * Implements hook_mail().
 */
function wateraid_tmgmt_mail($key, &$message, $params): void {

  if ($key == 'wateraid_tmgmt_error_notification') {
    $message['headers']['Content-Type'] = 'text/html';
    $message['headers']['From'] = \Drupal::config('system.site')->get('mail');
    $message['subject'] = new TranslatableMarkup('Smartling translation error report (@env)', [
      '@env' => $_ENV['AH_SITE_ENVIRONMENT'] ?? 'local',
    ]);

    $message['body'][] = $params['body'];
  }
}

/**
 * Implements hook_views_pre_view().
 */
function wateraid_tmgmt_views_pre_view(ViewExecutable $view, $display_id, array &$args): void {
  if ($view->id() != 'tmgmt_job_overview') {
    return;
  }

  $id = 'tmgmt_job_bulk_form';

  // If the handler exists in the view, get it.
  if ($handler = $view->getHandler($view->current_display, 'field', $id)) {

    // Now delete so we don't put the broken handler back.
    $view->removeHandler($view->current_display, 'field', $id);

    // Then get the other handlers so we can put them back.
    $handlers = $view->getHandlers('field');

    // Clear everything out so the TMGMT handler can be first.
    foreach ($handlers as $name => $value) {
      $view->removeHandler($view->current_display, 'field', $name);
    }

    // Repair the handler's broken config.
    $handler += [
      'alter' => [],
      'empty_zero' => FALSE,
      'hide_empty' => FALSE,
      'empty' => FALSE,
      'element_default_classes' => [],
      'element_label_class' => '',
      'element_label_type' => '',
      'element_class' => '',
      'element_type' => '',
    ];

    // And add the fixed handler back.
    $view->addHandler($view->current_display, 'field', 'tmgmt_job', $id, $handler);


    // And finally all the others.
    foreach ($handlers as $name => $value) {
      $view->addHandler($view->current_display, 'field', 'tmgmt_job', $name, $value);
    }
  }
}
