<?php

/**
 * @file
 * Module file for wateraid_forms.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Form\FormStateInterface;
use Drupal\wateraid_forms\WateraidFormsUrl;
use Drupal\webform\WebformSubmissionForm;

/**
 * Implements hook_theme_registry_alter().
 */
function wateraid_forms_theme_registry_alter(&$theme_registry): void {
  // Allow an actions variable in the webform_progress theme.
  if (!isset($theme_registry['webform_progress']['variables']['actions'])) {
    $theme_registry['webform_progress']['variables']['actions'] = NULL;
  }
}

/**
 * Implements hook_page_attachments().
 */
function wateraid_forms_page_attachments(array &$attachments): void {
  // Attach the URL parameters from config as a Javascript setting.
  $url_parameter_keys = _wateraid_forms_get_url_parameters();
  $attachments['#attached']['drupalSettings']['wateraidForms'] = ['url_parameters' => $url_parameter_keys];
  $attachments['#attached']['library'][] = 'wateraid_forms/wateraid_forms_urls';
}

/**
 * Get an array of url/cookie parameters.
 *
 * @return mixed[]
 *   URL parameters.
 */
function _wateraid_forms_get_url_parameters(): array {
  /** @var \Drupal\webform\WebformThirdPartySettingsManagerInterface $third_party_settings_manager */
  $third_party_settings_manager = \Drupal::service('webform.third_party_settings_manager');

  $default_url_parameters = implode(PHP_EOL, WateraidFormsUrl::WATERAID_URL_PARAMETERS);

  $url_parameters = $third_party_settings_manager->getThirdPartySetting('wateraid_forms', 'url_parameters', $default_url_parameters);

  // Clear any /r.
  return explode("\n", str_replace("\r\n", "\n", $url_parameters));
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alter the webform export form to set the default exported to be wateraid_csv.
 */
function wateraid_forms_form_webform_results_export_alter(&$form, FormStateInterface $form_state, $form_id): void {
  $form['export']['format']['exporter']['#default_value'] = 'wateraid_csv';
}

/**
 * Implements hook_webform_submission_form_alter().
 */
function wateraid_forms_webform_submission_form_alter(array &$form, FormStateInterface $form_state, $form_id): void {
  foreach (_wateraid_forms_get_url_parameters() as $param) {
    $form[$param] = [
      '#type' => 'hidden',
    ];
  }

  if (!empty($form['actions']['submit']['#submit']) && is_array($form['actions']['submit']['#submit'])) {
    array_unshift($form['actions']['submit']['#submit'], 'wateraid_forms_webform_submission_submit_handler');
  }

  if (!empty($form_state->getUserInput())) {
    $form['#attributes']['class'][] = 'form-has-user-input';
  }
}

/**
 * Form process callback to set the url_params field.
 *
 * @param mixed[] $form
 *   The form array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state object.
 */
function wateraid_forms_webform_submission_submit_handler(array &$form, FormStateInterface $form_state): void {
  // Get elements values from webform submission.
  /** @var \Drupal\webform\WebformSubmissionForm $form_object */
  $form_object = $form_state->getFormObject();
  /** @var \Drupal\webform\Entity\WebformSubmission $webform_submission */
  $webform_submission = $form_object->getEntity();

  $param_values = array_intersect_key($form_state->getValues(), array_flip(_wateraid_forms_get_url_parameters()));

  $webform_submission->set('url_params', $param_values, FALSE);
}

/**
 * Implements hook_entity_base_field_info_alter().
 */
function wateraid_forms_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type): void {
  if ($entity_type->id() === 'webform_submission') {
    // Add a base field to webform_submission entities.
    $fields['url_params'] = BaseFieldDefinition::create('map')
      ->setName('url_params')
      ->setLabel(t('Url parameters'))
      ->setTargetEntityTypeId('webform_submission');
  }
}

/**
 * Implements hook_form_alter().
 */
function wateraid_forms_form_alter(&$form, &$form_state, $form_id) {
  // Check if this is a webform submission form.
  if ($form_state->getFormObject() instanceof WebformSubmissionForm) {

    // Get the category from the webform.
    $categories = $form_state->getFormObject()->getWebform()->get('categories');

    // Add category as a class to the form if it exists.
    if (!empty($categories)) {
      $form['#attributes']['class'][] = 'webform-category-' . Html::getClass(implode(' ', $categories));
    }
  }
}
