<?php

/**
 * @file
 * Hooks and other functionality for the WA DAM.
 */

use Drupal\Core\Datetime\DrupalDateTime;

/**
 * Implements hook_cron().
 */
function wa_orange_dam_cron(): void {
  $now = new DrupalDateTime();
  $day = $now->format('N');

  if ($day == 7) {

    // Run the populator every Sunday.
    \Drupal::queue('wa_orange_dam_queue_populator')->createItem('wa_orange_dam_usage_processor');
  }
  elseif ($day == 1) {

    // And the notifications every Monday.
    \Drupal::queue('wa_orange_dam_notification_populator')->createItem(TRUE);
  }

  // And the expiry checker every cron run.
  \Drupal::queue('wa_orange_dam_queue_populator')->createItem('wa_orange_dam_expiry_checker');
}

/**
 * Implements hook_preprocess_HOOK().
 */
function wa_orange_dam_preprocess_field(&$variables): void {
  if (isset($variables['element']['#field_name']) && $variables['element']['#field_name'] === 'field_dam_expiry_date') {
    if (isset($variables['items'][0]['content']['#context']['value'])) {
      $date_formater = \Drupal::service('date.formatter');
      try {
        $variables['items'][0]['content']['#context']['value'] = $date_formater->format($variables['items'][0]['content']['#context']['value'], 'wateraid_fixed_donation');
      }
      catch (\Exception $e) {
        \Drupal::logger('wa_orange_dam')->error('Error formatting DAM expiry date: @message', ['@message' => $e->getMessage()]);
      }
    }
  }
}

/**
 * Implements hook_mail().
 */
function wa_orange_dam_mail($key, &$message, $params): void {
  if (in_array($key, ['systems_admin', 'node_author'])) {
    $message['headers']['Content-Type'] = 'text/html';
    $message['headers']['From'] = \Drupal::config('system.site')->get('mail');
    $message['subject'] = $params['subject'];
    $message['body'][] = $params['message'];
  }
}
