<?php

/**
 * @file
 *  Hooks and other functionality for the WA DAM.
 */

/**
 * Implements hook_cron().
 */
function wa_orange_dam_cron(): void {
  $queue = \Drupal::queue('wa_orange_dam_expiry_checker');
  $query = \Drupal::database()->select('media_field_data', 'm')
    ->fields('m', ['mid'])
    ->condition('m.bundle', [
      'dam_file',
      'dam_image',
      'dam_video',
    ], 'IN');
  $query->leftJoin('media__field_dam_expired', 'e', 'e.entity_id = m.mid');

  $or = $query->orConditionGroup();
  $or->condition('e.field_dam_expired_value', 1, '<>');
  $or->isNull('e.field_dam_expired_value');

  $query->condition($or);
  $query->leftJoin('media__field_dam_last_checked', 'l', 'l.entity_id = m.mid');
  $query->orderBy('l.field_dam_last_checked_value');
  $query->range(0, 50);

  foreach ($query->execute()->fetchAll() as $result) {
    $queue->createItem($result->mid);
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function wa_orange_dam_preprocess_field(&$variables): void {
  if (isset($variables['element']['#field_name']) && $variables['element']['#field_name']) {
    if (isset($variables['items'][0]['content']['#context']['value'])) {
      $date_formater = \Drupal::service('date.formatter');
      $variables['items'][0]['content']['#context']['value'] = $date_formater->format($variables['items'][0]['content']['#context']['value'], 'wateraid_fixed_donation');
    }
  }
}
