webform.settings.third_party.wateraid_donation_forms:
  type: mapping
  label: 'Webform test third party settings'
  mapping:
    message:
        type: mapping
        label: 'Message'
        mapping:
          value:
            type: text
            label: 'Message - Value'
          format:
            type: string
            label: 'Message - Format'
