display:
  default:
    display_title: Default
    display_options:
      fields:
        type:
          label: ପ୍ରକାର
        link:
          label: Operations
      exposed_form:
        options:
          submit_button: Filter
      filters:
        type:
          expose:
            label: ପ୍ରକାର
