<?php

/**
 * @file
 *  Hooks and functions related to WaterAid Groups.
 */

use Drupal\group\Entity\GroupInterface;
use Drupal\path_alias\PathAliasInterface;

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function wateraid_group_path_alias_presave(PathAliasInterface $path_alias): void {
  $path = $path_alias->getPath();

  // If the alias is in some way linked to a Group...
  if ($group = wateraid_group_get_from_drupal_path($path)) {
    //$path_alias->set('langcode', 'und');
  }
}

/**
 * Load the group from a group or relationship internal path.
 *
 * @param string $path
 *   The path to check for.
 *
 * @return \Drupal\group\Entity\GroupInterface|null
 * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
 * @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException
 */
function wateraid_group_get_from_drupal_path(string $path): ?GroupInterface {
  $group = NULL;

  if (str_starts_with($path, '/group/')) {
    $gid = substr($path, 7);

    /** @var \Drupal\group\Entity\GroupInterface $group */
    $group = \Drupal::entityTypeManager()->getStorage('group')->load($gid);
  }
  elseif (str_starts_with($path, '/group-relationship/')) {
    $rid = substr($path, 20);

    /** @var \Drupal\group\Entity\GroupRelationshipInterface $relationship */
    $relationship = \Drupal::entityTypeManager()
      ->getStorage('group_relationship')
      ->load($rid);
    $group = $relationship->getGroup();
  }

  return $group;
}

