<?php

/**
 * @file
 * Install, update, and uninstall functions.
 */

/**
 * Implements hook_install().
 *
 * Install all features in the "Wateraid" bundle.
 */
function wateraid_site_manager_testing_install(): void {
  drupal_static_reset('system_rebuild_module_data');
  $available_modules = \Drupal::service('extension.list.module')->getList();
  $dependencies = [];
  foreach ($available_modules as $name => $module) {
    if ($module->info['package'] === 'wateraid') {
      $dependencies[] = $name;
    }
  }
  \Drupal::service('module_installer')->install($dependencies);
}
