<?php

/**
 * @file
 * Wateraid site manager module file.
 */

/**
 * Implements hook_toolbar_alter().
 */
function wateraid_site_manager_toolbar_alter(&$items): void {
  $items['system.admin_wateraid'] = [
    '#attached' => [
      'library' => [
        'wateraid_site_manager/toolbar',
      ],
    ],
  ];
}

/**
 * Implements hook_theme().
 */
function wateraid_site_manager_theme(): array {
  return [
    'wateraid_features_uninstall' => [
      'render element' => 'form',
      'file' => 'system.admin.inc',
      'path' => 'core/modules/system',
      'template' => 'templates/system-modules-uninstall',
      'base hook' => 'system_modules_uninstall',
      'preprocess functions' => [
        'template_preprocess',
        'template_preprocess_system_modules_uninstall',
        'contextual_preprocess',
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_html().
 */
function wateraid_site_manager_preprocess_html(&$variables): void {
  $country_code = \Drupal::config('system.date')->get('country.default');

  // Set HTML lang attribute.
  switch ($country_code) {
    case 'MZ':
      $variables['html_attributes']['lang'] = 'pt';
      break;

    case 'JP':
      $variables['html_attributes']['lang'] = 'ja';
      break;

    case 'SE':
      $variables['html_attributes']['lang'] = 'sv';
      break;

    case 'DK':
      $variables['html_attributes']['lang'] = 'da';
      break;
  }
}
