<?php

/**
 * @file
 *   Functions and hooks for the Migrations.
 */

/**
 * Helper function to copy the existing migrations for a new site.
 *
 * @param array $suffixes
 *   An array of suffixes for the new migrations.
 */
function wa_migration_copy_migrations(array $suffixes = []): void {

  $config_factory = \Drupal::configFactory();
  $uuid_service = \Drupal::service('uuid');
  $migration_groups = $config_factory->listAll('migrate_plus.migration_group');
  $migrations = $config_factory->listAll('migrate_plus.migration.');

  foreach ($suffixes as $site) {
    foreach ($migration_groups as $group) {
      $config = $config_factory->getEditable($group);

      // Only copy the NG migrations.
      if (str_contains($config->getName(), '_pk')) {
        $data = $config->getRawData();

        $data['uuid'] = $uuid_service->generate();

        $data['id'] = str_replace('_pk', '_' . $site, $data['id']);
        $data['label'] = str_replace(' PK ', ' ' . strtoupper($site) . ' ', $data['label']);
        $data['description'] = str_replace('/pk', '/' . $site, $data['description']);

        foreach ($data['shared_configuration'] as &$shared_config) {
          foreach ($shared_config as $key => $value) {
            $shared_config[$key] = str_replace('pk', $site, $value);
          }
        }

        $name = str_replace('pk', $site, $config->getName());

        $clone = clone $config;

        $clone->setName($name);
        $clone->initWithData($data);
        $clone->save();
      }
    }

    foreach ($migrations as $migration) {
      $config = $config_factory->getEditable($migration);

      if (str_contains($config->getName(), '_pk')) {
        $data = $config->getRawData();

        $data['uuid'] = $uuid_service->generate();

        $data['id'] = str_replace('_pk', '_' . $site, $data['id']);
        $data['label'] = str_replace(' PK', ' ' . strtoupper($site), $data['label']);
        $data['migration_group'] = str_replace('pk', $site, $data['migration_group']);

        foreach ($data['process'] as &$processors) {
          if (isset($processors['migration'])) {
            if (is_array($processors['migration'])) {
              foreach ($processors['migration'] as $key => $name) {
                $processors['migration'][$key] = str_replace('_pk', '_' . $site, $name);
              }
            }
            else {
              $processors['migration'] = str_replace('_pk', '_' . $site, $processors['migration']);
            }
          }
          elseif (is_array($processors)) {
            foreach ($processors as &$processor) {
              if (isset($processor['migration'])) {
                if (is_array($processor['migration'])) {
                  foreach ($processor['migration'] as $key => $name) {
                    $processor['migration'][$key] = str_replace('_pk', '_' . $site, $name);
                  }
                }
                else {
                  $processor['migration'] = str_replace('_pk', '_' . $site, $processor['migration']);
                }
              }
            }
          }
        }

        if (isset($data['migration_dependencies']['required'])) {
          foreach ($data['migration_dependencies']['required'] as $key => $name) {
            $data['migration_dependencies']['required'][$key] = str_replace('_pk', '_' . $site, $name);
          }
        }

        $name = str_replace('pk', $site, $config->getName());

        $clone = clone $config;

        $clone->setName($name);
        $clone->initWithData($data);
        $clone->save();
      }
    }
  }
}

/**
 * Implements hook_cron().
 */
function wa_migration_cron(): void {

  // Manually trigger the queue so that we can create one file every cron run,
  // as the API process is a little slow and we don't want to choke it.
  $queue = \Drupal::queue('wa_migration_washmatters_files');

  if ($queue_item = $queue->claimItem()) {

    /** @var \Drupal\Core\Queue\QueueWorkerInterface $queue_worker */
    $queue_worker = \Drupal::service('plugin.manager.queue_worker')
      ->createInstance('wa_migration_washmatters_files');

    try {
      // Process only 1 queue item per cron run.
      $queue_worker->processItem($queue_item->data);
      $queue->deleteItem($queue_item);
    }
    catch (\Exception $e) {
      \Drupal::logger('wa_migration')->error(t('Error processing queue item: :error', [
        ':error' => $e->getMessage(),
      ]));
    }
  }
}
